### ISSUE TITLE
Using the grouping card breaks the tree in designer, breaks editor

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#105]
Using the grouping card causes the designer to display unexpected results in the node tree, and the editor fails to load the node tree.![grouping card in designer.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/8ceb5578-0d28-45f1-adcd-9cdcedb9ad5c)![grouping card breaks editor.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/cd1df35e-a7e1-438c-a82e-aa1af4a05551)

**Comment by dwuthrich** [comment]
@apeters you can reproduce this error by selecting the GLHER_Consultations model, opening the desiger, and clicking on Communications

**Comment by apeters** [comment]
see archesproject/arches#5045
