### ISSUE TITLE
Mapbox API key in package

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1068]
There is a Mapbox API key in the package perhaps left over from some initial testing (?).  
It should be removed as it gives the impression that Arches (and/or AfHER) comes with a Mapbox API key.

**Comment by aj-he** [comment]
@SDScandrettKint we are preparing a new 7.5 instance that will be excluding the key. We'll be getting a working branch in place soon.

**Comment by aj-he** [comment]
Closed complete in #1079
