### ISSUE TITLE
Site visit workflow updates

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#108]
No address is needed on the first step and no map is needed in the site visit workflow.

The first step of the Site Visit workflow should include:

Name (Location Description?)
Visit Date
Related Consultation

**Comment by whatisgalen** [comment]
to be complete needs #90

**Comment by whatisgalen** [comment]
appears to meet ticket requirements -- transferring to qa

**Comment by chiatt** [comment]
Meets requirements
