### ISSUE TITLE
Consultation workflow updates

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#109]
Step 1 should be the related application area map selector
Step 2 should be the log date and target date
Step 3 should be the consultation location (map should zoom to the location of the related application area)

**Comment by whatisgalen** [comment]
Communicated with @dwuthrich and separated consultation details from consultation dates into two distinct steps.

**Comment by chiatt** [comment]
Hey @whatisgalen, I think you mentioned this is done given that there already is a ticket for selecting related resources with the map, right?

**Comment by whatisgalen** [comment]
@chiatt yes, that's correct

**Comment by chiatt** [comment]
works as expected
