### ISSUE TITLE
v75 Upgrade - Confirm how help documentation will be handled and implement

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches-her#1111]
Check which mechanism will be used for providing help documentation
Implement solution

**Comment by csmith-he** [comment]
Discussion email sent to confirm approach with making the Help Documentation available

**Comment by aj-he** [comment]
@csmith-he - discussed some changes to the introductory document with KB. Awaiting new version before being ready for review

**Comment by aj-he** [comment]
completed in #1312
