### ISSUE TITLE
v75 upgrade - bng-filter - add close button and fix popup styling

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1119]
Fix styling issues with the bng-filter and add a close button. Ensure the close button functionality and refocusing matches other popup panels.

![Image](https://github.com/archesproject/arches-her/assets/25295526/3645f4db-cfcc-4026-9f76-d5de1e512cb0)

**Comment by csmith-he** [comment]
@aj-he would this be one for @phudson-he to take a look at?

**Comment by aj-he** [comment]
yes, or at least with his guidance

**Comment by aj-he** [comment]
fixed in #1176
