### ISSUE TITLE
v75 upgrade - fixes area application workflow

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1126]

**Comment by aj-he** [comment]
I've noticed the map editor card Add/Cancel buttons are misaligned. Appears to be an issue with its container's fixed position...


![Image](https://github.com/archesproject/arches-her/assets/25295526/ceccb1f8-44db-4d36-a635-9bf0fedb931c)



![Image](https://github.com/archesproject/arches-her/assets/25295526/717ebb41-55df-4c7d-ad58-ab3056306dc3)

**Comment by aj-he** [comment]
There is also an issue with the Area designation step (which is a "many" step) where String and Url datatypes appear to not be made into observables and break the ability to edit a previously saved card.


![Image](https://github.com/archesproject/arches-her/assets/25295526/e770aac1-fdc0-4f19-84fe-9fd6958ba4a6)

![Image](https://github.com/archesproject/arches-her/assets/25295526/becb202d-3384-4535-a2de-dbf800e5ddd6)

**Comment by aj-he** [comment]
The Applications Area workflow not longer uses the app-area-address-step so this is being removed.  The other issues found seem to be core issues and will need raising separately there.

**Comment by csmith-he** [comment]
Fixed by #1129
