### ISSUE TITLE
v75 update Selected Consultation does not persist in Communication workflow once selected

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches-her#1135]
When a related consultation is selected in the first step of the Communication workflow, the selection does not persist when the following parts of the step are rendered in the browser:

Consultation selected:

![Image](https://github.com/archesproject/arches-her/assets/38533555/3a2068de-6605-4302-ab40-40eee9dd7e69)

Consultation selection not displayed when Date, Subject and Type are rendered visible as there is now a resourceid value in the view model:

![Image](https://github.com/archesproject/arches-her/assets/38533555/8d149622-2522-4fa4-a2fd-ea93c818bf92)

**Comment by csmith-he** [comment]
@chiatt - Added you as an assignee for now after the chat over on Slack, basically so you can find it easily.

**Comment by aj-he** [comment]
closed complete in #1178
