### ISSUE TITLE
v75 upgrade - report scrolling appears to be broken

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1153]
Reports don't have the ability to scroll on the y axis as shown in the video below with tabs that have data spanning longer than the screen view:

https://github.com/archesproject/arches-her/assets/119508494/18053563-293c-4e7e-8b14-dcd1d17f3c15

Also could be a general Arches page view height issue, as the version info on the navbar disappears with longer pages?

**Comment by phudson-he** [comment]
Being worked on under #1107 - will keep this here for now until reviewed and merged etc

**Comment by aj-he** [comment]
fixed in #1168
