### ISSUE TITLE
v75 upgrade - Consultation Report - Add communication button should not show in report

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1157]
The Communications section of the correspondance tab shows the "Add communitcations" button because their is a missing "if" in the data-bind for that element. Perhaps introduced in #1152 ?

![Image](https://github.com/archesproject/arches-her/assets/25295526/4f311c18-f87c-4022-9c9d-d56daacfcd1d)

**Comment by csmith-he** [comment]
Fixed by #1158
