### ISSUE TITLE
Source number in "Citation" report table

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1161]
Should the Source Number get added to the citations table in the report, so it can be visible and ordered by number - similar to a bibliography?  Currently the default sort order is alphabetical on the source name.

Example:
![image](https://github.com/archesproject/arches-her/assets/119508494/ebaa0ccd-d14e-4a3d-a3ee-5133bc5a0562)

**Comment by Philbox** [comment]
This makes sense to me.

**Comment by aj-he** [comment]
@SDScandrettKint - I guess the question is whether you need to sort by source then number, which that table won't allow. I have no opinion as to whether the column is visible or not.

**Comment by aj-he** [comment]
fixed in #1165
