### ISSUE TITLE
v75 upgrade - Opening multiple panels causes overlapping

### ISSUE THREAD

**Issue by phudson-he** [archesproject/arches-her#1162]
Steps to re-produce:

1. Open search page
2. Open time filter panel
3. Open help panel

The resulting issue is this, notice the panels are overlapping...

![Image](https://github.com/archesproject/arches-her/assets/52997281/1feffa79-c8ec-4f8b-a4fc-fe3afe797f5f)

**Comment by aj-he** [comment]
Looks like this commit during accessibility jumped the z-index of the search panels to help with the closing. 

https://github.com/archesproject/arches/pull/9723/commits/054733953be62bcbda4eee1e42653cae9c870e5a

I am assuming that we could safely move the notification/help/provisional edit panels over the top (`z-index: 12000`?)

**Comment by aj-he** [comment]
Top level panels only use the view height so when in mobile stacked arrangement, they only go half way and create double scroll bars...



![Image](https://github.com/archesproject/arches-her/assets/25295526/f9cbd230-7a13-4dd7-b6f1-8c2c43a3de8b)

**Comment by aj-he** [comment]
fixed in #1193
