### ISSUE TITLE
v75 upgrade - Search panels height/scrolling issue

### ISSUE THREAD

**Issue by phudson-he** [archesproject/arches-her#1163]
Steps to reproduce:

1. Open search page
2. Open search export panel
3. Reduce your browser height

Scroll down and you'll see the container height doesn't cater for the overflow...

![Image](https://github.com/archesproject/arches-her/assets/52997281/9d3050e9-c437-45b6-b690-038319e099e6)

**Comment by csmith-he** [comment]
@phudson-he Are you happy for me to reassign this to you?

**Comment by phudson-he** [comment]
> @phudson-he Are you happy for me to reassign this to you?

@csmith-he Yes no problem

**Comment by phudson-he** [comment]
This is also a problem in core, issue raised [here](https://github.com/archesproject/arches/issues/11019)

**Comment by phudson-he** [comment]
PR raised for core fix [here](https://github.com/archesproject/arches/pull/11020)

**Comment by phudson-he** [comment]
Closing as fixed by https://github.com/archesproject/arches/pull/11020
