### ISSUE TITLE
Search tag doesnt word wrap

### ISSUE THREAD

**Issue by phudson-he** [archesproject/arches-her#1164]
Steps to re-produce:

1. Open search page
2. In the search box, find and select an item that is quite long

Results in the text not wrapping...

![Image](https://github.com/archesproject/arches-her/assets/52997281/7ff179f2-83c1-4202-90b4-fd1cf7f08739)

**Comment by apeters** [comment]
@phudson-he the section of the code that defines the template to use for the search tags is [defined here](https://github.com/archesproject/arches/blob/master/arches/app/media/js/bindings/term-search.js#L91-L124).  You might be able to play around with the styles or add classes to enable wrapping of the text, or allow the tag to grow in height.

**Comment by phudson-he** [comment]
@apeters Many thanks for the info, will take a look.
