### ISSUE TITLE
Associated Construction Phase in Component doesn't show anything in report

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1167]
Component with Associated Construction Phase node populated should show an association to that Construction Phase node in the report, but this appears as an empty field.

How it looks in the report:
![image](https://github.com/archesproject/arches-her/assets/119508494/1e2ab95d-646c-42dc-b4ad-9c1d2fb89263)

Showing that there is an association in the resource editor:
![image](https://github.com/archesproject/arches-her/assets/119508494/1c83530d-5bab-44ec-b4b5-288558608a63)

**Comment by csmith-he** [comment]
@SDScandrettKint - Just to check before I start looking at this, was this something you wanted someone else (i.e. me) to look at or were you planning on working on it?

**Comment by samuelscandrett** [comment]
Happy for you to look at it @csmith-he!

**Comment by samuelscandrett** [comment]
Fixed in #1172
