### ISSUE TITLE
v75 upgrade - Map cards in workflows show the Add/Delete/Cancel buttons over the top of the bottom bar.

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1169]
![Image](https://github.com/archesproject/arches-her/assets/25295526/c794420a-d968-410c-b444-11719ef9e3fa)

**Comment by aj-he** [comment]
Flex for the install-buttons class when in a workflow step needs removing

![Image](https://github.com/archesproject/arches-her/assets/25295526/37e99b97-4d6c-4570-8e96-8b33ac70d700)

**Comment by phudson-he** [comment]
Fixed with #1190
