### ISSUE TITLE
v75 upgrade - report view in the resource falls off the right, and top bar missing

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1174]
The report view in the resource is falling off the right hand side of the screen (1) and the top bar with the login, search, report, help buttons is missing (2).

![image](https://github.com/archesproject/arches-her/assets/119508494/58cb4afa-cd4d-4680-8dd0-196a11cfda8a)

Though the top bar comes back when a node is selected:

![image](https://github.com/archesproject/arches-her/assets/119508494/30b4da7e-bae9-4536-ae56-b671d2166383)

**Comment by phudson-he** [comment]
@SDScandrettKint could I ask you to pull the latest from the [1077 branch](https://github.com/archesproject/arches-her/tree/1077_upgrade_to_v75_core_arches) and re-check, as I believe this has been fixed by another merged issue. Thanks.

**Comment by samuelscandrett** [comment]
@phudson-he you are correct, this is now fixed, I'm happy to close this issue :)
