### ISSUE TITLE
Search screen - Resource Type dropdown items hidden.

### ISSUE THREAD

**Issue by gouthamrandhi** [archesproject/arches-her#1208]
**Steps to reproduce:**

- Login to AHER and navigate to search screen - http://localhost:8002/search?paging-filter=1&tiles=true&format=tilecsv&reportlink=false&precision=6&total=6257

- Click on the 'Resource Type' dropdown menu.

**Expected:** User is able to scroll to the bottom of the items in the dropdown.
**Actual:** Unable to scroll to the bottom items.

https://github.com/archesproject/arches-her/assets/131354127/cb150b38-db5a-46f2-a701-59b6ba40c34d

**Comment by aj-he** [comment]
fixed in core arches https://github.com/archesproject/arches/issues/11077
