### ISSUE TITLE
README.md incorrect link

### ISSUE THREAD

**Issue by RobOatesHistoricEngland** [archesproject/arches-her#1215]
In branch [1077_upgrade_to_v75_core_arches](/archesproject/arches-her/tree/1077_upgrade_to_v75_core_arches) the link [instructions relating to the GDAL_LIBRARY_PATH](https://arches.readthedocs.io/en/latest/installing/installation/#common-errors) is not correct. There are multiple #common-errors in the target document and that particular link isn't particularly helpful when orientating the user to setting up the `GDAL_LIBRARY_PATH`.

Suggest the link be set to [https://arches.readthedocs.io/en/latest/installing/installation/#create-a-project](https://arches.readthedocs.io/en/latest/installing/installation/#create-a-project)

**Comment by aj-he** [comment]
fixed in #1215
