### ISSUE TITLE
Concept values and Url nodes not correctly populating in multi card steps

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1218]
**Application Area - Designations step**

Concept and Url node values don't correctly move back and forth from the multi-card area on right.

1. Concept nodes show None in the multicard view.

![Image](https://github.com/archesproject/arches-her/assets/25295526/3e5ea943-e225-40d4-be14-a6a5573dbc5d)

2. When click on `edit` the concept AND url nodes do not correctly repopulate. This might only happen if you move to another step and then return to the Area Designation step and then click edit.

(picture TBC)

3. When saving a card, all values are cleared except the URL which persists the current value.

![Image](https://github.com/archesproject/arches-her/assets/25295526/1cf23e46-dd7a-448c-a6ce-34eb286ad348)

**Site Visit - Site Visit Attendees** 

Affects Attendee Type node

**Comment by csmith-he** [comment]
None for concepts is when a value hasn't been specified.  When a concept is selected, it can be repopulated without issue.

The URL node is a problem and I think it's to do with something in the URL object structure not being handled properly so this requires investigation.

**Comment by aj-he** [comment]
PR raised... https://github.com/archesproject/arches/pull/11138
