### ISSUE TITLE
Digital Object model - set the File node configuration Accepted Image Types to 'any file type'

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1219]
Set the File node configuration Accepted Image Types to 'any file type'

![Image](https://github.com/archesproject/arches-her/assets/25295526/5c9974ef-269a-4e88-9505-31e713ad7d3c)

change to...

![Image](https://github.com/archesproject/arches-her/assets/25295526/3099037e-dd3c-438b-9293-338542b80676)

**Comment by csmith-he** [comment]
I'll do this task as part of the wider graph change piece of work

**Comment by csmith-he** [comment]
Will be included in the pull request for #1211

**Comment by csmith-he** [comment]
On review, adding this to widget configuration stops files from being uploaded.  This appears to be a Core issue and will need to be fixed as such

**Comment by aj-he** [comment]
Core issue raised here - https://github.com/archesproject/arches/issues/11120

**Comment by aj-he** [comment]
fixed in core https://github.com/archesproject/arches/issues/11120
