### ISSUE TITLE
Site Visit Workflow - Help notice states incorrect button name

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1221]
The "Quit Workflow" button reference must be changed to "Delete" button.

![Image](https://github.com/archesproject/arches-her/assets/25295526/78eb3c96-f1d9-47ce-8ca6-d3092206f10c)

**Comment by csmith-he** [comment]
This appears to be in the Application Area, Communication, Consultation and Site Visit workflows so I will fix in all these

**Comment by aj-he** [comment]
fixed in #1225

**Comment by gouthamrandhi** [comment]
Tested and working as expected.
![image](https://github.com/archesproject/arches-her/assets/131354127/967684c1-61be-4d47-96f7-2f12cdc23be0)
