### ISSUE TITLE
Site Visits Workflow - Misaligned buttons in Site photo step

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1223]
when editing photo metadata, the save/delete/cancel buttons are misaligned

![Image](https://github.com/archesproject/arches-her/assets/25295526/2a9da626-1d94-40b4-bd62-54d093e0a227)

**Comment by phudson-he** [comment]
This is a core issue.

Issue raised: https://github.com/archesproject/arches/issues/11051
PR raised: https://github.com/archesproject/arches/pull/11052
