### ISSUE TITLE
SHINE Significance in Area Assignment even if assignment isn't SHINE related

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1229]
The node "SHINE Significance" always shows under Area Assignments, but in some situations this can be misleading/confusing if the assignment is unrelated to SHINE.

![image](https://github.com/archesproject/arches-her/assets/119508494/6fed76e5-e584-47a5-9515-654fea969fc1)

**Comment by aj-he** [comment]
fixed in #1230
