### ISSUE TITLE
Search Export: The email received do not have download link.

### ISSUE THREAD

**Issue by gouthamrandhi** [archesproject/arches-her#1233]
**Steps to reproduce:**

- Log in to AHER and navigate to search page.
- Selecting Bibliographic source from the resource type dropdown retrieves 2136 results.
- Now click search export and Export Search results pop up opens.
- Select the CSV checkbox, enter a valid HE email address and click download button.

**Expected**

- An email should be received with a download link.
- A notification should appear with download link in Bell icon section.

**Actual:** Email received do not have the download link on it. Bell icon notification is working as expected.

**Note:**  Used to receive an email for the above functionality previously but this morning did not receive the email too.

![image](https://github.com/archesproject/arches-her/assets/131354127/e6666195-45c6-4944-8cda-a1f7938974f2)

**Comment by csmith-he** [comment]
@gouthamrandhi - ready for checking

**Comment by aj-he** [comment]
fixed in #1239
