### ISSUE TITLE
AHER Accessibility- Home Page: 2.4.1- Bypass Blocks- No bypass block available

### ISSUE THREAD

**Issue by phudson-he** [archesproject/arches-her#1250]
**Given** I am a user reliant on keyboard to navigate the webpage
**When** I am on the AHER home page
**Then** There is no bypass block offered to me, requiring me to navigate through the navigation bar before I reach the content of the page

Bypass blocks are necessary to allow users to be able to skip to the main content of the page rather than having to tab through the navigation bar before reaching the content

**2.4.1- Bypass Blocks**
Allow people who navigate sequentially through content more direct access to the primary content of the Web page.
An example could be to provide a ‘Skip to Content’ link to bypass parts of the page not relevant to the user.

**Comment by aj-he** [comment]
@phudson-he - isn't this a duplicate of https://github.com/archesproject/arches-her/issues/1240 and merged in here https://github.com/archesproject/arches-her/pull/1235??

**Comment by phudson-he** [comment]
@aj-he Yes, closing
