### ISSUE TITLE
Hide workflow icons in the main navbar

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#126]
Workflow plugin icons should not be available in the main nav bar. Maybe this should be a plugin config that a plugin developer can easily specify.  

 ![Screen Shot 2019-08-12 at 2.53.33 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/361375af-7e8c-403a-93a3-a27340be0f14)

**Comment by ryan86** [comment]
meets requirements.
