### ISSUE TITLE
Accessibility- Report Page- Period: 1.4.10- Reflow- Tabs not reflowing

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1262]
When I have the "Period Names" tab selected and zoom into 400%, the tabs do not reflow and go off the edge of the screen. When done with any other tab selected, they reflow correctly

1.4.10- Reflow
The software should support people with low vision who need to enlarge text and read it in a single column. When the browser zoom is used to scale content to 400%, it reflows - i.e., it is presented in one column so that scrolling in more than one direction is not necessary. Content can be presented this way without a loss of information.

![Image](https://github.com/user-attachments/assets/c6976107-58f7-4a90-9dd8-65bf745d8742)

**Comment by phudson-he** [comment]
Closing as now fixed after updating local environment branches
