### ISSUE TITLE
Accessibility- Report Page- Period: 1.4.3- Contrast- JSON Tab Line numbers do not meet contrast requirements

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1263]
The colour contrast of the line numbers for the JSON files do not meet contrast requirements
only reaching a 2.63 when they are required to be 4.5

![Image](https://github.com/user-attachments/assets/9c637ae1-7e41-4a91-af87-e8bdaf4c4e76)

**Comment by phudson-he** [comment]
Fixed in https://github.com/archesproject/arches-her/pull/1268
