### ISSUE TITLE
Accessibility- Report Page- Activity: 1.4.4- Resize Text & 1.4.10- Reflow- Scroll bar not fully displaying the Json tab

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-her#1266]
When zoomed in to the point that the tabs of the reports page require a scroll bar, The scroll bar will not go fully to the end, cutting off the Json tab Partially 

![Image](https://github.com/user-attachments/assets/8d5048a7-b91e-48cd-9897-90217d319f73)

![Image](https://github.com/user-attachments/assets/f6bfad6b-a811-401b-bfd5-3126be2bad72)

1.4.4- Resize Text: 
Text can be resized to 200% without loss of content or function. Visually rendered text, including text-based controls (text characters that have been displayed so that they can be seen [vs. text characters that are still in data form such as ASCII]) can be scaled successfully so that it can be read directly by people with mild visual disabilities, without requiring the use of assistive technology such as a screen magnifier. Users may benefit from scaling all content on the Web page, but text is most critical.

1.4.10- Reflow
The software should support people with low vision who need to enlarge text and read it in a single column. When the browser zoom is used to scale content to 400%, it reflows - i.e., it is presented in one column so that scrolling in more than one direction is not necessary. Content can be presented this way without a loss of information.

**Comment by phudson-he** [comment]
Closing as fixed, screenshot attached...



![Image](https://github.com/user-attachments/assets/20d073da-824d-4eab-9135-6da31ff5b0b6)
