### ISSUE TITLE
Spelling issues in Consultation report

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1271]
Typo in Consultation Progression "Related Advice":
![image](https://github.com/user-attachments/assets/f4520fd7-8c43-455a-a89e-2d9df8397ac7)

And Advice Type all one word in the card:
![image](https://github.com/user-attachments/assets/6b4b2624-0117-47d7-aeb7-9ca84c8acd65)

**Comment by aj-he** [comment]
fixed in #1272
