### ISSUE TITLE
Adding Associated Consultation in Application Area resource causes console error

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1277]
Adding an associated consultation in an Application Area causes report to break
![image](https://github.com/user-attachments/assets/b5db5e7b-2869-44df-8a19-3f8f24db2d51)

**Comment by samuelscandrett** [comment]
More helpful log from Firefox:
![image](https://github.com/user-attachments/assets/c2f0ea03-c036-4e47-9ebf-b6b11e02fdf2)

**Comment by aj-he** [comment]
@SDScandrettKint @csmith-he - disabling paging in the table config fixes the issue, so it is something to do with paging. There are a couple of other reports/scenes that use paging and my very limited testing does not show the same error, but I suggest it is checked.

![Image](https://github.com/user-attachments/assets/a6d2615b-5369-4815-a31d-fb1f3af74b39)

**Comment by samuelscandrett** [comment]
Note: this issue is not specific to just associated consultations, but any associations that use the `relatedResourceTwoColumnTableConfig` table e.g. Consultations, Activities, Digital Files etc.

Update:  nevermind, it affects all tables in `resources.js`, as Associated Mons/Areas/Artefacts is also affected which has the table type `relatedResourceThreeColumnTableConfig`.  Strangely, the associated Application Areas table is not affected, which comes from it's own file `application-area.html` / `.js`
