### ISSUE TITLE
Bottom line of graph icon cut off for some graphs

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1280]
Some graphs have the bottom line of their icon cut off 
![image](https://github.com/user-attachments/assets/a0fe9532-296c-44bb-89d3-b5d1e2e1f017)

Others do not
![image](https://github.com/user-attachments/assets/391ab0a9-7244-4b56-9bd6-2b46220a5ba1)

Tested in Firefox and Chrome.  Changing zoom level also causes this issue for some icons, but fixes for others. 

Most likely a core issue.

**Comment by aj-he** [comment]
Is this a core issue or part of the AfHER code? If core can you raise there? Also, can you set the project status please.

**Comment by samuelscandrett** [comment]
Core Arches issue created https://github.com/archesproject/arches/issues/11291

Closing this issue as it isn't specific/relevant to the AfHER project.
