### ISSUE TITLE
Email received for password reset journey is missing information.

### ISSUE THREAD

**Issue by gouthamrandhi** [archesproject/arches-her#1291]
**Steps to reproduce:**

- User is on sign in screen of AFHER (local instance).
- Click on the 'Forgot Password' link.
- Enter valid email address and click on 'Recover my password' button.

**Expected**: An email should be received to reset password and should contain all the information.

**Actual**: The email received is missing information as shown in the below screenshot:

![image](https://github.com/user-attachments/assets/7c46b20a-60b3-4d13-8e97-ced1d32d74ea)

**Comment by gouthamrandhi** [comment]
@aj-he Could you please add a bug label to this issue.

**Comment by aj-he** [comment]
fixed in #1297
