### ISSUE TITLE
Resource delete button produces console error 

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1292]
The delete button in the resource table produces a console error once pressed, and the UI only reflects the row deletion once the page has been refreshed, and the tile is still visible in the node tree:

https://github.com/user-attachments/assets/a71d8aac-78b4-4ca8-8c23-0fbb9aa15865

This was not the case in the version 6 instance of AfHER.  In this version the row would be visibly deleted, and the tile would also disappear from the node tree:

https://github.com/user-attachments/assets/35faa1bc-4325-45d9-980f-cd3e1a17ee10

**Comment by aj-he** [comment]
Completed by #1337
