### ISSUE TITLE
Create a plugin to list available consultation instances

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#13]
If possible this component should be designed to apply to other resource types so that it could be introduced to core arches or easily applied in other packages.

![Screen Shot 2019-03-06 at 5.35.22 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/6c809e85-6ce4-42d6-bce8-71cbebdcb07b)

**Comment by apeters** [comment]
this is now superseded by #93 and #110
