### ISSUE TITLE
Map_sources using /geojson endpoint causing performance issues

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1317]
The map_sources found in [this file](https://github.com/archesproject/arches-her/blob/dev/1.0.x/arches_her/pkg/preliminary_sql/select_sources.sql) are using the geojson endpoint, which causes performance issues (specifically in the select-application-area source) when there are in the 10s of thousands of geometries.  E.g. an instance where there are ~40,000 application area geometries takes ~3mins to load.

These geojson endpoint requests are made each time the search page is loaded, and when the application area location card is loaded.  This causes the requests to stack up and slow down the entire Arches instance, sometimes having the power to crash it, until the requests have fufilled.

- The biggest culprit is the select-application-area source.  
- select-area is not referenced anywhere, and appears to be unused, however it is still called on /search.
- select-monument is used in the Application Area.json on lines [150](https://github.com/archesproject/arches-her/blob/4e30f4036fc981a9c7909c0e2a7cd98de3103997/arches_her/pkg/graphs/resource_models/Application%20Area.json#L150) and [532](https://github.com/archesproject/arches-her/blob/4e30f4036fc981a9c7909c0e2a7cd98de3103997/arches_her/pkg/graphs/resource_models/Application%20Area.json#L532), however, its nodeid is incorrect and thus must be old.

Other downstream effects of a long load of select-application-area area:
- Polygons not appearing in map resource editor cards, or not able to be selected to edit (shows a console error of `map is undefined`).
- Geometries cannot be added in the resource editor until these requests have fufilled.
- Basemaps cannot be switched whilst the request is in progress.
- Application Area location card doesn't show mapbox zoom buttons or "search for address" bar until fufilled.

**Comment by aj-he** [comment]
fixed in #1335
