### ISSUE TITLE
Can't save tiles when creating a new Application Area through the Consultation workflow

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1321]
Creating a new Application Area through the consultation workflow & map card appears to be broken, as tiles can't be saved, and sections of the map card still persist:

![image](https://github.com/user-attachments/assets/1537c624-c2e5-4477-b711-47aea8a82592)

When adding new Application Areas through the regular Consultations resource editor, sections of the map card still persist, but data is able to be saved:

![image](https://github.com/user-attachments/assets/b9839140-ebe6-4b1f-98ea-0b05e9f3bfc6)

Note, this is not the case for other "Create new X resource" in the workflows e.g. creating a new Maritime Vessel in the Application Area workflow "Related Heritage Resources" stage:

![image](https://github.com/user-attachments/assets/f3df6e1a-5595-44d5-8056-d665b6c34c27)

**Comment by csmith-he** [comment]
It looks as though there might be some sort of conflict between the container holding the UI for adding an application area and the container holding the map from the application area workflow.

The div holding the save button is in the code it just isn't visible on the screen which makes me wonder if it's been pushed into the overflow for some reason:


![Image](https://github.com/user-attachments/assets/e405b362-36c8-458c-887a-5934df9763d2)


Might be one for @phudson-he to look at on Monday?

**Comment by aj-he** [comment]
completed by #1325
