### ISSUE TITLE
AfHER using LatLong/WGS84 ANALYSIS_COORDINATE_SYSTEM_SRID rather than BNG

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1332]
The settings.py variable ANALYSIS_COORDINATE_SYSTEM_SRID is set to lat/long rather than BNG.  This means that any map filtering either via the BNG search feature or the default map filter is done to Lat/Long and different to BNG.

**Comment by aj-he** [comment]
completed by #1333
