### ISSUE TITLE
Error when trying to import multiple tiles per resource in CSV importer

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1336]
Attempting to import multiple tiles per resource, as shown in the docs [here](https://arches.readthedocs.io/en/stable/developing/reference/import-export/#csv-import) and like the image below, is not possible with the AfHER models.  

![image](https://github.com/user-attachments/assets/9b39ef7c-8940-4fce-8af6-8a77746d3392)

This is because the ResourceID column is not only used for identifying the resource to be imported, but it is also used as a node in the System Reference Numbers nodegroup.  When trying to import multiple tiles, a cardinality error (`Multiple Tiles for Cardinality-1 Nodegroup`) arises because the system is attempting to add a new tile to the System Reference Numbers nodegroup, but this isn't possible.  The cardinality of this nodegroup is correct, but the column names being identical means the system is conflicting with itself.

**Comment by aj-he** [comment]
@SDScandrettKint - you can use the mapping file to give the ResourceID node a different column name, and then use that name for the column in the CSV.

**Comment by samuelscandrett** [comment]
@aj-he I can confirm this works.  Changing the mapping file line `"file_field_name": "ResourceID",` from ResourceID to another column name fixed it, as the CSV can now use ResourceID for the resourceinstanceid only, not the node.

I'll close this issue, but it might be useful to document somewhere in case others face the same issue in the future.
