### ISSUE TITLE
create workflow step to handle Correspondence - Letter node 

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-her#137]
the Letter node (file-list datatype) should... 
-- receive the value of the preceding step's Letter Type tile value
-- load a populated docx template file from the django view 
-- ideally show the newly generated file as appended to the node's file-list widget, alongside other pre-existing files

related: #39

**Comment by whatisgalen** [comment]
it is also necessary to place this node in a separate card (so as to load in a separate step), thus impacting the graph for Consultation

**Comment by whatisgalen** [comment]
Needs #132 for testing

**Comment by whatisgalen** [comment]
remaining work:
-- finalize and upload the rest of the docx templates to the project_root/docx/directory
-- write methods in `file_template.py` to handle those templates
-- (optional) implement `insert_custom()` and `insert_image()` methods for those use cases

one side note was that after I had tested this several dozen times, the `get` request in the view was not able to find tiles for the list `letter_tiles` (ln 48) and I could not figure out what was causing it but I suspect there were issues with the dummy data I was using since on package re-load I no longer saw this issue.

**Comment by chiatt** [comment]
meets requirements
