### ISSUE TITLE
Create a card component to display and edit photos in a workflow

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#14]
A card component is needed to add and modify photos in a resource instance. The component should have a list of photo tiles that belong to the target resource instance displayed in a carousel panel at the base of the component. When a user selects a tile, that tile's input widgets (for name, caption, rights) should be displayed in a panel on the right and the image should be displayed on the left:
<img width="500" alt="IIIF Card Component I" src="https://user-images.githubusercontent.com/1877663/55176884-4097f200-513f-11e9-9d16-b843c2249b9a.png">
<img width="500" alt="IIIF Card Component II" src="https://user-images.githubusercontent.com/1877663/55176899-47bf0000-513f-11e9-8840-4609a59fa4f9.png">

**Comment by dwuthrich** [comment]
@chiatt aren't you working on this?  Not sure why this ticket is ready for QA

**Comment by dwuthrich** [comment]
meets requirement
