### ISSUE TITLE
Create a component that inserts and instance's tile data into a docx template and renders it in the browser

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#15]
Check with @dwuthrich for templates and latest mockups

**Comment by whatisgalen** [comment]
This is definitely doable with something like this package: https://docxtemplater.readthedocs.io/en/latest/
An example workflow would be to load a docx file with {var_name} and then docxtemplater would replace with some value in a json obj such as { var_name: 'Foo' }, effectively akin to a mail merge.
In a previously researched python library for docx you can also iterate through the different docx object types, e.g. paragraph, table, picture. Also re: that research, it seems like libreOffice has a standalone python script (which seems like it could run without having to install a full distribution of libreOffice) called unoconv for format conversion: https://github.com/unoconv/unoconv

In any case, putting this ticket on hold pending further definition of the needed implementation.

**Comment by chiatt** [comment]
The task described in this ticket is now divided between #38 and #39. The recommendations described in this ticket will be used to address #38
