### ISSUE TITLE
Active consultations pages all consultations instead of just active ones

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#158]
Active consultations should only attempt to show currently active consultations.  Active consultations are define as those with the following labels in the status node:

Active
Active*  (e.g.: the word "Active" followed by other strings)
Project Initiation
Post-excavation Assessment

**Comment by whatisgalen** [comment]
The options for Consultation Status are limited to:
- Aborted
- Completed
- Dormant
- Mitigation
- Post-excavation assessment
- Pre-decision assessment/evaluation
- Project Initiation
- Publication & Archiving

As of right now, active consultations loads any consultation whose status is not Aborted or Completed.

**Comment by dwuthrich** [comment]
closing in favor of #218
