### ISSUE TITLE
Active Consultations map should show location of consultation

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#160]
Currently the grid item shows the basemap, but not a circle for the consultation location

**Comment by whatisgalen** [comment]
add geojson from map node, if possible from related application area as well

**Comment by dwuthrich** [comment]
@whatisgalen This does not seem to work for all consultations.  See attached screen shot.  Also, we should show all maps at a defined (and configurable?) zoom level.  Currently the map can be so zoomed in to not really show a meaningful geospatial area.  Perhaps the default zoom level for the map in active consultations is z=18.
<img width="1622" alt="Screen Shot 2019-09-16 at 9 26 08 PM" src="https://user-images.githubusercontent.com/815185/65011522-a54f3080-d8c8-11e9-8556-648d4f30c475.png">

**Comment by dwuthrich** [comment]
Note: it looks like just the last consultation in the list of active consultations show the location

**Comment by dwuthrich** [comment]
meets reqiurements
