### ISSUE TITLE
Create a workflow step that will store another node's value or a custom string 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#17]
This would specifically be used to allow a user to save a consultation address as the consultation name.

<img width="1131" alt="screen shot 2019-03-07 at 5 11 33 pm" src="https://user-images.githubusercontent.com/1877663/54000414-1f258680-40fc-11e9-817f-8727e647dc4f.png">

**Comment by dwuthrich** [comment]
meets requirements
