### ISSUE TITLE
Workflow header and middle panel content

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#206]
Workflow header should show the correct icon associated with each workflow and the workflow step panel should show the workflow name, not "Insert Workflow Name"![Screen Shot 2019-09-06 at 3.56.12 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/c47f97cd-47c6-44f9-b1af-46d5c2e523a8)

**Comment by chiatt** [comment]
Meets requirements
