### ISSUE TITLE
Update style of selectable steps to indicate that a step is selectable. 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#213]
See mockup. Pointer should indicate this as well.

**Comment by dwuthrich** [comment]
This functionality still isn't right.  If a user is on a step that does not require input (for example, the associated monuments step in the New Application Area workflow), the UI should indicate that the user may proceed to the next step by styling the icon for the next step in the nav bar and enabling the right arrow in the step description panel

**Comment by dwuthrich** [comment]
meets requirements
