### ISSUE TITLE
tile data from rich text widget retains html tags in docx template

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-her#214]
this is specific to tile data showing up in a populated docx template

**Comment by whatisgalen** [comment]
noted occurrences: output in populated docx template

**Comment by whatisgalen** [comment]
This is almost complete -- when tile data for the Proposal node has a table in it, there's still an issue loading it in LibreOffice where an error states that some data is corrupted, but no such error loading it in Mac's texteditor which shows the table as expected.

**Comment by chiatt** [comment]
Fixed in the latest
