### ISSUE TITLE
Correspondence workflow allows user to proceed without defining a template.

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#240]
The first step of the Correspondence workflow allows a user to select a template and a consultation. If a user advances without selecting a template, the workflow can still advance without it. This will cause an error later in the workflow. 

The first step should not be 'complete' until a user has selected a template.

**Comment by whatisgalen** [comment]
this node is now "required" which prevents the user from proceeding, but see #272 regarding response in the UI for when a user tries to proceed anyway

Note: Package reload is required for this change to take effect, cc @dwuthrich

**Comment by dwuthrich** [comment]
meets requirement
