### ISSUE TITLE
Display tile data in tabular form in reports

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#241]
Add a card config to indicate that data will be rendered in tabular form in tabbed reports. The table will apply only to designated card. Child cards will not be displayed in the table.

**Comment by whatisgalen** [comment]
note that there is likely work to be scoped at the card level re: styling, e.g. https://github.com/archesproject/consultations-prj/issues/336

**Comment by dwuthrich** [comment]
closing for now as @whatisgalen noted that additional work will be required to fully resolve this issue
