### ISSUE TITLE
Fix active consultations URL

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#247]
When attempting to return to the consultations UI from Arches, the URL loads into the wrong UI:  https://recordit.co/sCi9LAUzXK

**Comment by dwuthrich** [comment]
@chiatt Can you please expedite this ticket?  It really has been a lingering issue and makes a seamless demo of consultations very difficult

**Comment by chiatt** [comment]
@dwuthrich Namjun is working on this first thing this morning.

**Comment by dwuthrich** [comment]
meets requirement
