### ISSUE TITLE
Consultations vertical nav bar state

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#263]
The default state of the vertical nav bar should be "expanded".  It should remain expanded until the user decides to collapse the bar.  It should then remain collapsed until the user decides to expand it again

**Comment by dwuthrich** [comment]
This is still a problem as shown here: https://recordit.co/gaSNTEw0jh

Note vertical panel changes state during page load, and icon/consultations label at top of vertical menu changes inappropriately

**Comment by dwuthrich** [comment]
entire page now seems to reload when navigating

**Comment by chiatt** [comment]
Consultations nav bar replaced by default nav bar
