### ISSUE TITLE
trying to proceed in a step without entering required data shows no warning/alert

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-her#272]
two ideas would be to either disable the "add" (i.e. "next") button until tile for that node exists, or throw an alert on tile-validation of empty data for required nodes

**Comment by whatisgalen** [comment]
related: https://github.com/archesproject/arches/issues/5273

**Comment by chiatt** [comment]
@whatisgalen This is working for me now that #5273 is resolved.

**Comment by whatisgalen** [comment]
Verified that trying to proceed throws an error in the UI and unable to proceed. Closing
