### ISSUE TITLE
Can't delete a consultation instance

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#279]
see: https://recordit.co/uHRmO5n3nU

**Comment by chiatt** [comment]
I noticed this is only a problem when the workflows nav bar is present. From the standard editor a user can delete an instance.

**Comment by chiatt** [comment]
Resolved by fixing the alert notification banner.

**Comment by dwuthrich** [comment]
Consultation deletion is now supported, but the app returns the user to an unexpected location (e.g.: core Arches new resource instance screen).  When deleting a consultations instance from the consultations endpoint, the user should be returned to the workflows page

**Comment by dwuthrich** [comment]
meets requirements
