### ISSUE TITLE
Create placeholder workflows and wire them up to the 'Create New' page

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#28]
The workflows indicated in the screenshot below should be created (they can basic workflows can be stubbed out even if their graphs aren't ready). A user should be able to click on an workflow icon to start editing a workflow. Use the workflows created in #33 and #34 if they are created already.

![Screen Shot 2019-05-01 at 4.25.13 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/ca15bc7d-4bc2-4c2b-8820-b5247e3c3137)

**Comment by dwuthrich** [comment]
meets requirements
