### ISSUE TITLE
Wire up completed resource instances to the active consultations page 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#31]
![Screen Shot 2019-05-02 at 10.25.52 AM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/20a6ef66-fe94-41f4-bb5f-1acaa9cd7ee6)

**Comment by dwuthrich** [comment]
@whatisgalen The way to determine whether a Consultation instance should appear on the active consultations page is to look at the Consultation Status node value.  

If the value is anything other than "Completed" or "Aborted", the consultation should be listed on the page
