### ISSUE TITLE
UUIDs shown instead of display identifier for related actors in Consultations workflow

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#310]
Editor shows UUIDs in the card tree instead of display name after completing the Consultations workflow.![Screen Shot 2019-09-26 at 9.20.57 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/7b8d03b1-ef5b-4ef5-b58e-bc02f9840e90)

**Comment by chiatt** [comment]
@dwuthrich Can you verify that you are still seeing this bug? @njkim and I have both been unable to reproduce it on the latest.

**Comment by dwuthrich** [comment]
meets requirements
