### ISSUE TITLE
Improve UX for moving to next step in a workflow 

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#313]
Many steps in a workflow present forms where input is optional.  However, we only show an "Add" button as the way to move to the next step in the workflow (see screen shot).  We should update the button text to "continue" in this case.  Also, the next step in the workflow top panel should be highlighted (in the light grey style shown in the mockup) to indicate to the user that they can move to the next step in the workflow![Screen Shot 2019-09-26 at 9.29.56 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/4f3a6394-94af-4579-8270-d8a624d66b16)

**Comment by aj-he** [comment]
@dwuthrich this looks like it is no longer relevant? Can it be closed?

**Comment by chiatt** [comment]
@aj-he You're right - the workflows UI has evolved a great deal since this ticket. If there are issues related to informing the user about the workflow state, they should probably be addressed in a new ticket.
