### ISSUE TITLE
related application area geometry UX in consultation workflow

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-her#351]

**Comment by whatisgalen** [comment]
When creating a new consultation instance via the workflow:
After selecting a related application area in the first step, the second step shows geometry associated with the application area, however this geometry is not selectable and therefore does not get added to the tile saved by that step, thus a tile thusly gets saved: `{'cons-map-node-id': None}`, thus causing the error.

**Comment by robgaston** [comment]
@whatisgalen what error are you referring to when you say "causing the error"? I don't see any other mention of an error in this ticket.

@dwuthrich: Do we actually want to add that geometry to the tile? the geometry is shown as per your request in this issue comment: https://github.com/archesproject/consultations-prj/issues/197

We could easily allow a user to select application area geometries (including the related one) as we do currently on the application area map card.  IMHO preemptively adding the application area geometry to the consultation map card seems presumptuous.

**Comment by whatisgalen** [comment]
@robgaston I agree pre-emptively adding geometry would be presumptuous. I think from a UX standpoint, a non-savvy user might assume that the related-application-area geometry has indeed been added since the map gives a visual cue to that effect (even though it is a different color). 

I guess at worst, this ticket points out that it's a little confusing as to what geometry is or isn't added to the consultation at this point, also due in part to the fairly subtle appearance of the geometries as line-items on the right-hand panel.

**Comment by robgaston** [comment]
I think that we can close this out for now and chock the UX issue up to one of training.  I'm doing so on the basis that @dwuthrich QA'd and closed out #197 last week.
