### ISSUE TITLE
Consultations: can't access site when logging in with account other than admin

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#370]
Consultations allows you log in with an account other than admin.  However, clicking the menu options (e.g.: new, find, active) raises an error and the user can't advance past the splash screen.

Pressing the manage button does take the user to Arches default UI

**Comment by whatisgalen** [comment]
Pausing this due to the following unanswered questions:
1) Is there a way to grant a user group/role permission to one plugin and not another?
2) should all user groups for a project by default have the "view all plugins" permission (aka `view_plugin`)?
cc @apeters @robgaston @dwuthrich
