### ISSUE TITLE
Trying to define related condition node in mitigations causes error

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#378]
See: https://recordit.co/2EhdeZej9W

**Comment by whatisgalen** [comment]
@dwuthrich this change requires a package load given that it was a change to the model.

**Comment by dwuthrich** [comment]
This error still appears when trying to reference a condition

**Comment by dwuthrich** [comment]
confirming that this issue is still not fixed

**Comment by whatisgalen** [comment]
working in latest

**Comment by dwuthrich** [comment]
This still is not working and fails with the following error

![Screen Shot 2020-03-02 at 2 05 07 PM](https://user-images.githubusercontent.com/815185/75722340-e2e52180-5c8e-11ea-92c6-2854ad7d1799.png)

**Comment by Philbox** [comment]
Is this the same issue as we are experiencing when trying to associate a component with a construction phase. the node value appears to work but the 'Loading failed' message appears when trying to add a construction phase

**Comment by chiatt** [comment]
There is no longer a mitigation branch - is it possible that the branch was simply renamed and this problem still persists?  In either case, this doesn't appear to be an issue with the node-value datatype itself as the datatype works as expected when relating a Communication with an Advice node: 

![image](https://user-images.githubusercontent.com/1877663/146935151-482dd2a9-e345-4b68-baa2-ebc0e13c7a40.png)

**Comment by chiatt** [comment]
Closing as there is no longer a mitigation branch.
