### ISSUE TITLE
Card component for saving correspondence letters.

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#39]
Write a card component that allows a user to select a docx template, and upon selection makes a request to the server for a populated version of the template. Alternatively a user can simply upload a file using the standard file widget. In either case, the file will be saved a node in the card's tile.

re #15

**Comment by whatisgalen** [comment]
Needs #132 for testing

**Comment by whatisgalen** [comment]
I think this ticket was obviated by #137
