### ISSUE TITLE
Consultations Workflow does not name new consultation properly

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#408]
After completing the consultation workflow with no errors, opening the newly created instance in editor reveals that it was not named properly (associated app area name is missing from cons name) as shown:

![Screen Shot 2019-10-29 at 2.37.13 PM.png](https://images.zenhubusercontent.com/56f1ad a0a6caf56c9d38e1cbd/91729418-5136-4051-8638-f635a6b46239)

**Comment by whatisgalen** [comment]
working in latest

**Comment by dwuthrich** [comment]
meets requirements
