### ISSUE TITLE
Active Consultations no longer working

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#417]
After completing the new consultation workflow successfully, the consultation is not displayed in the active consultations page

**Comment by whatisgalen** [comment]
it looks like the Consultation Status function isn't being called when it's supposed to. I'll fix this.

**Comment by whatisgalen** [comment]
@dwuthrich I just pushed a fix and it works again but will require a package load

**Comment by dwuthrich** [comment]
fixed
