### ISSUE TITLE
bugs in Add new resource on-the-fly in workflows

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-her#45]
When adding a new resource in a workflow step, (via "Create new [Application Area, Communication, etc.]" ) the elements for this feature do not obscure the form elements behind it.

<img width="485" alt="Screen Shot 2019-05-30 at 2 25 47 PM" src="https://user-images.githubusercontent.com/8366985/58666620-b3ad1880-82e8-11e9-9266-1d1183ae1b47.png">

**Comment by ryan86** [comment]
meets requirements

![Screen Shot 2019-06-24 at 11 51 32 AM](https://user-images.githubusercontent.com/3038476/60044059-6e290480-9676-11e9-86df-1f13ce0dcca8.png)

**Comment by chiatt** [comment]
Unfortunately I am seeing this problem in the contacts workflow step of the consultation workflow.

**Comment by chiatt** [comment]
<img width="442" alt="Screen Shot 2019-07-09 at 1 12 37 PM" src="https://user-images.githubusercontent.com/1877663/60919715-4a0b1d00-a24b-11e9-8d5a-387ab285ad00.png">

**Comment by whatisgalen** [comment]
committed a change to the css so that this shows up on top. not behind the card widget.

One note is that one of the cards where this was occurring was in Consultations (workflow and resource editor) for the Contacts card. Adding a new "Actor - Person" yielded an empty modal where the user is supposed to be able to enter data for a new resource. This issue was caused by a bug related to the concept collection not being recognized by the widget for an unknown reason, nonetheless separate and distinct from the css-related issue visible in the screenshot, addressed by my PR.

**Comment by ryan86** [comment]
meets requirements.
