### ISSUE TITLE
No field to define which Borough an Application Area is in

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches-her#452]
### describe the issue
When creating an Application Area, there is currently no field to define which Borough the area is in.

Will this be done automatically based on the spatial data? Sometimes there will not be any spatial data and therefore there will need to be an option to add the borough manually.

![borough](https://user-images.githubusercontent.com/47248246/74819228-f8a23080-52f7-11ea-8a6e-b49376c0fa1f.png)

**Comment by chiatt** [comment]
Hi @rebecca23williams, I don't see a Borough node in Address branch of the current Application Area resource model.

**Comment by rebeccawilliamss** [comment]
Hi @chiatt, this came from initial user feedback. I've checked with both Laura and Phil and they have said that they would like a Borough node added. They also said that it doesn't necessarily need to be part of the Address, but it will help when searching for Application Areas that fall in a particular Borough (e.g how many application areas are there within the borough of Camden).

**Comment by Philbox** [comment]
Hi @chiatt as you mentioned the resource model doesn't have a borough node in the Address branch.
The borough information is contained in the Administrative Areas branch (see image). This branch can be accessed by editing the Application Area via the Resource Manager but cannot currently be added to via the consultations workflow

![image](https://user-images.githubusercontent.com/16647003/77080541-4f7f5080-69f1-11ea-8148-400197a3447d.png)

**Comment by Philbox** [comment]
Sorry sent previous message too soon. SO in essence the consultations workflow for Application Area needs to include the Admin Areas branch on one of the tabs.

In an ideal world this data would be taken straight out of the OS Boundary Line data held in ArcGIS and based on the address or geometry.

**Comment by StucakeGLHER** [comment]
Hi @chiatt @Philbox @rebeccawilliamss This, having a card in the Application Area workflow to record admin areas, seems to be un-necessary.  Arches now automatically populates the Localities/AdminAreas branch once the spatial area of the AA has been created (it is currently also creating a blank Non Parish Area), and obviously the Localities/AdminAreas branch can be edited through the Resource card anyway.

**Comment by chiatt** [comment]
Thanks @StucakeGLHER, given that, I'm going to close this issue for now
