### ISSUE TITLE
Inactive Consultations showing up on Active Consultations page

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches-her#455]
Consultations with a status set to inactive are still showing up on the Active Consultations page. 

#### Consultation set to inactive
![inactiveconsultation](https://user-images.githubusercontent.com/47248246/75154337-6938bb00-5705-11ea-88a3-dc9e89948100.png)

#### Consultation showing up in Active Consultations
![inactiveconsultations](https://user-images.githubusercontent.com/47248246/75153640-cc295280-5703-11ea-94c0-07990808777c.gif)

**Comment by rlwilliamss** [comment]
Closing this as no longer an issue.
