### ISSUE TITLE
error saving Actor Organization

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-her#458]
Data validation error when trying to save tile to Name node

**Comment by whatisgalen** [comment]
The widget hard coded into the relevant card for this graph was concept-multi-select ("10000000-0000-0000-0000-000000000012") even though the datatype was Concept, not ConceptList.

**Comment by whatisgalen** [comment]
A ticket in core arches was created as a result of work done for this ticket:
https://github.com/archesproject/arches/issues/5943

**Comment by dwuthrich** [comment]
meets requirement
