### ISSUE TITLE
Which card is the Application Area using for name when it is created via the resource manager

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches-her#469]
#### Issue Description
Currently some of the Application Area records are appearing nameless in the search results. The nameless test records were created via the Resource Manager rather than through the workflow. Which card should the model be using as the records name? Should it be the Address card?

#### Steps to reproduce
1) Open the search page and search for the record 'Covent Garden Market'. The record will appear nameless in the search results

2) Edit the record to open the resource editor and click on the Addresses card. The card is filled out, so which card should be used for the record's name?
![NamelessAA](https://user-images.githubusercontent.com/47248246/78132283-62901880-7414-11ea-99e9-0fcb33a3f17c.png)
![AAAddressCard](https://user-images.githubusercontent.com/47248246/78132302-691e9000-7414-11ea-96e6-078a2417e315.png)

**Comment by dwuthrich** [comment]
This is a configuration issue.  Resolved by updating the descriptor function for the model

**Comment by Philbox** [comment]
@rebeccawilliamss This appears to have been solved in dev keystone as I can't replicate it. In your screenshot there is no Application Area Names Card but in Dev there is
