### ISSUE TITLE
ConnectionResetError when saving Maritime GLHER Geometry card

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches-her#471]
#### Issue Description
Saving the GLHER Geometry card for Maritime results in a Connection Reset Error.

#### Steps to reproduce
1) Create a new Maritime record from the resource manager http://qa.archesproject.org/resource

2) Click on the GLHER Geometry card and add a point on the map, within the London area

3) Save the card

![image](https://user-images.githubusercontent.com/47248246/78136851-34163b80-741c-11ea-9dc1-22f87a8801bd.png)

**Comment by dwuthrich** [comment]
Can not reproduce.  Probably resolved in the last revision for this model
