### ISSUE TITLE
TypeError when saving Maritime National Grid Reference card

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches-her#472]
#### Issue Description
A TypeError occurs when saving the National Grid Reference card for Maritime resource. The screenshot below shows the example Alphanumeric BNG.

#### Steps to reproduce
1) Open the create resource page and select to create a new Maritime resource 

2) Once the resource editor has opened, click on the National Grid Reference card

3) Set the Coordinate Format to Alphanumeric BNG

4) Enter TQ4305879748 into the text box field and click on the green Add button - a TypeError occurs and is displayed at the top of the page
![TypeError NGR](https://user-images.githubusercontent.com/47248246/78137161-bc94dc00-741c-11ea-88da-abb5c4d5e4cc.png)

**Comment by dwuthrich** [comment]
Can not reproduce.  Likely resolved when the BNG data type was updated
