### ISSUE TITLE
TileValidationError when saving the Status card for an Aircraft resource

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches-her#473]
#### Issue Description
When creating a new Aircraft resource and saving the Status card, you get a 'TileValidationError: Multiple domain values were found for '0a362f4e-1de0-4913-896b-105777e0b5b5' . Please use an explicit id instead of a domain string value. This data was not imported.'

#### Steps to reproduce
1) Open the create new resource page and select to create a new Aircraft resource http://dev-cons-keystone.historicengland.org.uk/resource

3) Click on the Status card and select either Casualty or Site as the input 

4) Click on the green Add button

![image](https://user-images.githubusercontent.com/47248246/78150294-038bcd00-742f-11ea-9215-23efefe033ea.png)

**Comment by dwuthrich** [comment]
Can not reproduce.  Likely resolved with last update to the BNG data type
