### ISSUE TITLE
PermissionError when saving a document in the Correspondence workflow

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches-her#479]
#### Issue Description
A PermissionError occurs when saving an uploaded document in the Communications workflow, and the document is not saved.

![image](https://user-images.githubusercontent.com/47248246/78555077-2e499d00-7804-11ea-99ef-a9522f85543e.png)

**Comment by chiatt** [comment]
I suspect the issue here might be the user permissions on the docx (`/arches_her/docx`) directory in arches_her. That directory likely needs the same permissions as the uploadedfiles directory.

**Comment by chiatt** [comment]
Closing as this is a server configuration issue rather than something that can be changed in Arches or HER.
