### ISSUE TITLE
ConnectionResetError at /search

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches-her#480]
#### Issue Description
When navigating to the Keystone Search page from the Manage page, a ConnectionResetError occurs. This error does not occur every time, however it is frequent. Page reload fixes error.

#### Steps to reproduce
1) Open the QA home page http://qa.archesproject.org/

2) Click on Manage

3) Navigate to the Search page via the left navigation bar

![ConnectionResetError](https://user-images.githubusercontent.com/47248246/78661522-d3c54500-78c6-11ea-8537-d2f4012e4cb4.png)

**Comment by dwuthrich** [comment]
Can not reproduce
