### ISSUE TITLE
Review Heritage Asset Model

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#481]
a general review of the heritage asset model regarding its semantics.

**Comment by Habennin** [comment]
since I cannot use the assign function, I hereby declare myself the asssignee and mention @Philbox

**Comment by Philbox** [comment]
I have assigned us both

**Comment by Habennin** [comment]
thanks! so this being the first thing we're looking at, I forgot to create a git branch. I have done two things: made a long list of remarks on each of the branches in your models and what I see as being useful or no to change. I have also edited the model directly but again without having created a fork. Here's the google doc with the commentary:

https://docs.google.com/document/d/1DJlkdmgqKuI2H9R4NLc6rkN_M_qkBIciYzUxIwVgjDw/edit?usp=sharing

want me to just export the model for now so you can take a look at it?

**Comment by dwuthrich** [comment]
@Habennin @Philbox can this ticket be closed?

**Comment by Philbox** [comment]
This can be closed
