### ISSUE TITLE
Review Actor Person Model

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#483]
review of actor person model in view of general review of models for publication push

I created a comment file here:

https://docs.google.com/document/d/1Zp-mFyy8mYzYl3GkyK1n4oFrtVLUWNTxIPOfDlLN8ws/edit?usp=sharing

Can discuss before edits

@Philbox can you assign us etc.?

**Comment by Habennin** [comment]
Final Review in here:

https://docs.google.com/document/d/1Zp-mFyy8mYzYl3GkyK1n4oFrtVLUWNTxIPOfDlLN8ws/edit#heading=h.6q8815e31g7d

It looks great.

Over to you: @Philbox

**Comment by Habennin** [comment]
@Philbox and @Habennin reviewed together. Await final json upload

**Comment by Philbox** [comment]
@Philbox added metatypes and review recommendations

Final json here: https://drive.google.com/open?id=1R1QQwZFqGncOIWIBH2hoAmzIOEpKGvfv

@Habennin check it out

**Comment by Habennin** [comment]
@Philbox and @Habennin reviewed. Ready for push to repo

**Comment by Philbox** [comment]
Final Json here:

https://drive.google.com/open?id=1gYWmEnPpLNVUXvwcScyCLzMsCZxGwbxI

@dwuthrich over to you for technical review

**Comment by Habennin** [comment]
Data Entry Review done.

**Comment by dwuthrich** [comment]
@Habennin @Philbox can this ticket be closed?
