### ISSUE TITLE
Review Activity Asset Model

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#484]
General review of Activity Asset Model for Semantic Harmonization

https://docs.google.com/document/d/1WaWqZw9kKhxIcXWWQMRV5vkg2tOSijmZWyXQF_G7mMo/edit?usp=sharing

Tag me when you are looking at this, @Philbox

**Comment by Habennin** [comment]
Final Json push reviewed, see discussion doc. Ready for final discussion and then push to repo

@Philbox have a look at the minor comments when you can

**Comment by Habennin** [comment]
Ran a data entry review check. You can see results in discussion doc at end @Philbox

**Comment by dwuthrich** [comment]
@Habennin @Philbox can this ticket be closed?
