### ISSUE TITLE
Review Archive Source Model

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#485]
General semantic review and harmonization of this model

tag me when you are at this @Philbox 

https://docs.google.com/document/d/1bXIUz1lytaE82qSmbIzGimQZ76R_qD4iwp9hWTifCHo/edit?usp=sharing

**Comment by Habennin** [comment]
New Json produced by @Philbox after initial review.

New json reviewed by @Habennin  on 25/5/2020

Results here:

https://docs.google.com/document/d/1bXIUz1lytaE82qSmbIzGimQZ76R_qD4iwp9hWTifCHo/edit?usp=sharing

**Comment by Habennin** [comment]
Third review carried out. All minor fixes entered. Ready for push to repo in my mind. I take it you concur @Philbox ?

**Comment by Habennin** [comment]
Ran a data entry review check. You can see results in discussion doc at end @Philbox

**Comment by dwuthrich** [comment]
@Habennin @Philbox can this ticket be closed?
