### ISSUE TITLE
No way to name a Consultation when creating a new workflow

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches-her#487]
### User Feedback/Suggestion

There is currently no way to name a Consultation when creating a new Consultation via the workflow. You can edit the name of a Consultation once it has been created in the resource editor. 

Not being able to name Consultations when creating them means that multiple Consultations within the same Application Area will have the same name unless they are edited.

**Comment by dwuthrich** [comment]
The workflow automatically creates the consultation name as a concatenation of the application area name and the date.  @rebeccawilliamss Is this acceptable?

**Comment by rlwilliamss** [comment]
@dwuthrich Yes, I think this was down to a missunderstanding of how the names are automatically created, I will close this issue.
