### ISSUE TITLE
Create Correspondence Workflow

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#49]
See Consultations mockup for steps and refer to the latest DISCO mockups for UX

disco mockup: https://www.dropbox.com/s/vft1pc40nwgjhxu/DISCO%20Workflows%20v5.pdf?dl=0
consultations mockup: https://www.dropbox.com/s/5ebao8033oqp7i7/Consultations%20v5.pdf?dl=0

**Comment by chiatt** [comment]
The correspondence resource model is needed to proceed with this ticket

**Comment by dwuthrich** [comment]
@chiatt There's a correspondence branch in the consultations model that should be sufficient for the workflow.  Pull the latest consultations-prj for the updated model

**Comment by whatisgalen** [comment]
For this to be complete, still need the select-resource ticket (#90 ) and the letters card component (#39  )

**Comment by chiatt** [comment]
The outstanding tasks mentioned above are addressed by other tickets. The correspondence workflow exists, so I'm closing this ticket.
