### ISSUE TITLE
Application Area Review

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#491]
This task is created to track a general review of the semantics of the application area model for HER. 

The comment document has been generated here:

https://docs.google.com/document/d/1MCYk6wsU_y61RaZmF3eOSDTc-XpDgX1JfmRXj5i7gqc/edit?usp=sharing

This task is being undertaken by George Bruseker and @Philbox

**Comment by Habennin** [comment]
@Philbox delivered reviewed json
@Habennin has reviewed the revision, ready for new discussion and next/final json upload

**Comment by Philbox** [comment]
@Philbox added metatypes to all branches following 2nd Review.

Final json here: 

https://drive.google.com/open?id=1sfFc_Ztr_v51CKS4njMnbNRFW9vvatwn

Over to you @Habennin for final review

**Comment by Habennin** [comment]
co-review by @Philbox and @Habennin , agreed and scheduled for push to repo

**Comment by Philbox** [comment]
Final Json here:

https://drive.google.com/open?id=1Yy8dBpbQIYKUCwvXdsZ6yQECV3Nh0Ctv

@dwuthrich over to you for technical review

**Comment by Habennin** [comment]
Ran a data entry review check. You can see results in discussion doc at end @Philbox

**Comment by dwuthrich** [comment]
Closing, as superseded by #679
