### ISSUE TITLE
Artefact Model Review

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#492]
This task is generated in order to track a general review of the semantics of the artefact model. 

The comment document has been created here:

https://docs.google.com/document/d/1xWMKgrAmZzKOxDkzX5SvuoCw4FMARuP9nS0gwq14Tc4/edit?usp=sharing

This task is undertaken by George Bruseker and @Philbox

**Comment by Habennin** [comment]
The revised json has been reviewed by @Habennin, now can be checked by @Philbox for final json production

**Comment by dwuthrich** [comment]
@Philbox Is this still an issue?
