### ISSUE TITLE
Bibliographic Source Model Review

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#493]
This task is created to track the process for the general review of the semantics of the bibliographic source model. 

The commentary document is created here:

https://docs.google.com/document/d/1mpQxBiQizMZRMQCWQzH5IX0ZaAVpuDr5eAxetAsIfsQ/edit?usp=sharing

But all the information is also in the very long issue description above!

This task is undertaken by George Bruseker and @Philbox

**Comment by Habennin** [comment]
@Philbox uploaded to second review stage.
@Habennin executed second review, check it out.

**Comment by Philbox** [comment]
@Philbox implemented recommendations of second review

Final json here:
https://drive.google.com/open?id=17v_KmN8xUS9tO8PuYqh_WR7yMSXbI9yg

@Habennin check approach for Authorship etc in Bibliogrpahic Source Creation branch

**Comment by Habennin** [comment]
Co review with @Philbox and @Habennin , agreed minor changes and schedule for push to repo

**Comment by Philbox** [comment]
Final Json here:

https://drive.google.com/open?id=1Ek-5_aRqm2jhhyZ6VPN_f1KkReSf48RT

@dwuthrich over to you for technical review

**Comment by Habennin** [comment]
Ran a data entry review check. You can see results in discussion doc at end @Philbox

**Comment by dwuthrich** [comment]
Closing
