### ISSUE TITLE
Create Digital Object Resource Model

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#494]
In the course of the general semantic data model review (could be an 'epic') we decided to investigate the possibility of creating a general digital object resource model for the user. Following up on this I (George Bruseker) have created a first sketch of what this can look like, to discuss with @Philbox .

The doc can be found here:

https://docs.google.com/spreadsheets/d/1hX-W5Xx5QfkxYv91vVyh2_P7sSJRYxtxK1mq3o8rVVE/edit?usp=sharing

**Comment by Habennin** [comment]
Model implemented by @Philbox 

Implemented model reviewed by @Habennin 

Review Here:

https://docs.google.com/document/d/1rSVmAc80O38TUlNVKgZzFNuX3HJ-R7z58TBzB7V7qtU/edit

**Comment by Habennin** [comment]
co review by @Philbox and @Habennin , no issues, scheduled for push to repo

**Comment by Philbox** [comment]
Final Json here:

https://drive.google.com/open?id=15H3_1BifPRNOvgCil3yM6hqC8WiEBv7O

@dwuthrich over to you for technical review

**Comment by Habennin** [comment]
Ran a data entry review check. You can see results in discussion doc at end @Philbox

**Comment by dwuthrich** [comment]
meets requirements
