### ISSUE TITLE
review consultations model

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#495]
review the model for semantic consistency

https://docs.google.com/document/d/1ijSlITHGXwYF97lAzIr0ZptOTcAj65NeHUEQVULkxLg/edit?usp=sharing

**Comment by Habennin** [comment]
@Philbox created new json based on first review
@Habennin reviewed new json

over to @Philbox to look at second review.

**Comment by Philbox** [comment]
@Philbox implemented recommendations of Review 2

@Habennin check for semantics. Actor relationships re roles remain unchanged. Discussion re .1 properties or PCxx solution needs to be had with @dwuthrich et al

**Comment by Philbox** [comment]
@Philbox implemented slight revision.

Latest Final json here:
https://drive.google.com/open?id=1xnUYeoapg73Jg-1c2oUkQmG_q5kaPYuR

Addition of partitioned groups for contacts and metatypes
@Habennin confirm approach

**Comment by Habennin** [comment]
co-reviewed by @Philbox and @Habennin , agreed to minor change, as documented in review doc, and scheduled for push to repo

**Comment by Philbox** [comment]
Final Json here:

https://drive.google.com/open?id=18KbdR1813JnfCnvYekFpN9Lunbb3cb1d

@dwuthrich over to you for technnical review

**Comment by dwuthrich** [comment]
meets requirements
