### ISSUE TITLE
heritage subject and themes model review

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#497]
review the semantics of this model for consistency

https://docs.google.com/document/d/15r3edg6TLaXSf0xA3dWngsEqxRXKgs8zWYaGAKI44ZI/edit?usp=sharing

**Comment by Habennin** [comment]
Final Json push reviewed, see discussion doc. 

The one small issue is how to model the associated images.

Ready for final discussion and then push to repo

@Philbox have a look at the minor comments when you can

**Comment by Habennin** [comment]
Ran a data entry review check. You can see results in discussion doc at end @Philbox

**Comment by dwuthrich** [comment]
@Habennin @Philbox Is this still an issue?
