### ISSUE TITLE
Create Communication Workflow

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#50]
See Consultations mockup for steps and refer to the latest DISCO mockups for UX

disco mockup: https://www.dropbox.com/s/vft1pc40nwgjhxu/DISCO%20Workflows%20v5.pdf?dl=0
consultations mockup: https://www.dropbox.com/s/5ebao8033oqp7i7/Consultations%20v5.pdf?dl=0

**Comment by apeters** [comment]
fixed in the latest
