### ISSUE TITLE
Create Period Model

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#500]
Decision was taken to create a period model (instead of storing this data in RDM) in order to be able to fully and semantically correctly represent relevant period data.

**Comment by Habennin** [comment]
@Philbox has created json, and @Habennin has reviewed. Check out 'second review' in review doc here:


https://docs.google.com/document/d/11p36dVNznnchmP3F3ETWLCVH6emEYaC7Bu1uHu-XcqI/edit#

**Comment by Philbox** [comment]
@Philbox made adjustments to final model and added Metatypes following discussion with @Habennin
Final json here:

https://drive.google.com/open?id=1l3ezZSPRCDZb_v80Q2-rHoe_DYpe5DMj

**Comment by Philbox** [comment]
Resource Model renamed Period from Historic_Period to reflect non-historic nature of time itself...

**Comment by Habennin** [comment]
Hey @Philbox ... if you start talking about historicity of time, you are definitely infected with some intriguing 18th century notions.

Anywho, I looked it over one more time and it looks great to me. I comment this also in the discussion doc. 

I think this is ready for a push to repo

**Comment by Habennin** [comment]
coreviewed by @Philbox and @Habennin , minor changes done in place and agreed. Scheduled for push to repo

**Comment by Philbox** [comment]
Final Json here:

https://drive.google.com/open?id=1rwc6wRi4JVVFvy57V2LlszBjs2cCreT2

@dwuthrich over to you for technical Review

**Comment by Habennin** [comment]
I added a data entry review on the review document

https://docs.google.com/document/d/11p36dVNznnchmP3F3ETWLCVH6emEYaC7Bu1uHu-XcqI/edit#

to see @Philbox

**Comment by dwuthrich** [comment]
@Habennin @Philbox Is this still an issue?
