### ISSUE TITLE
Review Organization Model

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-her#505]
Review Organization Model:

https://docs.google.com/document/d/1U0bWY4YgT8qEhOplbGnJv8ViH-he17kJu88Dzg5ncBM/edit

Semantically harmonize and role out final model for production

**Comment by Habennin** [comment]
Final model delivered by @Philbox 

Review here:

https://docs.google.com/document/d/1U0bWY4YgT8qEhOplbGnJv8ViH-he17kJu88Dzg5ncBM/edit

**Comment by Philbox** [comment]
Actor_Organization superseded by Organization following addition of metatypes.

Final json here: https://drive.google.com/open?id=1Q_9y1pU7dTvTV_39cco7-YGZHZBMZwbV

@Habennin give this a quick review.

**Comment by Habennin** [comment]
co reviewed by @Philbox and @Habennin , agreed complete and scheduled for push to repo

**Comment by Philbox** [comment]
Final json here:

https://drive.google.com/open?id=19QDxxf5YX0aWIkQgDCczRYn4pZH-lmJn

@dwuthrich over to you for technical review

**Comment by Habennin** [comment]
Ran a data entry review check. You can see results in discussion doc at end @Philbox

**Comment by dwuthrich** [comment]
meets requirements
