### ISSUE TITLE
Option to sort Active Consultations by Target Date

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches-her#506]
#### User Feedback Description
When on the “Active Consultations” page it would be best if the default was to sort the consultation by Target date with the earliest target dates (so the ones that are due for completion soonest) being first. At the moment this is not an option in the “Sort by…” drop down.

**Comment by chrisdolby-HE** [comment]
This is actually more important to the consultation process than the log date.

It is on the rare side, but some consultations are given more time to progress due to extenuating circumstances.

**Comment by rlwilliamss** [comment]
In addition to sorting by Target Date, users would also like to be able to sort by Borough/Admin Area.

**Comment by dwuthrich** [comment]
superseded by #678

**Comment by chrisdolby-HE** [comment]
@dwuthrich, #678 doesn't include these two points in the description. Please can you confirm whether or not these are being looked at?
