### ISSUE TITLE
Unable to complete a new Application Area workflow

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches-her#508]
#### Issue Description
The Application Area workflow final step is blank and you're unable to click on the finished button.

![ApplicationAreaNotSaving](https://user-images.githubusercontent.com/47248246/82995066-05bb7380-9ffb-11ea-8f85-ccbaee4cff4b.gif)

**Comment by dwuthrich** [comment]
resolved with latest workflow
