### ISSUE TITLE
Active consultations plugin: sorting by date is reversed

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#515]
@dwuthrich commented on [Wed Mar 11 2020](https://github.com/archesproject/arches/issues/5974)

In the active consultations plug-in, sorting by date is reversed.  Selecting "Log Date: newest to oldest" lists the oldest logged consultation first.  Selecting "Log Date: oldest to newest" lists the newest first

**Comment by njkim** [comment]
It appears to the same issue as #678
