### ISSUE TITLE
Addition of a pre-existing branch to another branch causing error

### ISSUE THREAD

**Issue by Philbox** [archesproject/arches-her#516]
When adding a branch to another branch the new branch won't save any node except the root node if the 'Place node(s) in separate card' is toggled to off.

1. Open any branch to be modified (eg. Designation and Protection Assignment)
2. Select Root Node
3. Click 'Add branch' icon - Branch library opens
4. Select Type branch
5. Select 'P2 has type'
6. Toggle 'Place node(s) in a separate card' to off

![image](https://user-images.githubusercontent.com/16647003/85846853-6080f000-b79e-11ea-9117-7d4a53418fca.png)

7. Save edits
8. Click cards tab - New branch nodes appear on card.

![image](https://user-images.githubusercontent.com/16647003/85846934-87d7bd00-b79e-11ea-873a-91289beb4138.png)

9. Quit Designer
10. Open branch again
11. The root node Type appears in the graph and card but not the child node

![image](https://user-images.githubusercontent.com/16647003/85847056-b9e91f00-b79e-11ea-94ee-3a3a3d4bd6d5.png)

![image](https://user-images.githubusercontent.com/16647003/85847113-cec5b280-b79e-11ea-98b1-5770fd9919fa.png)

This change in functionality has happened following recent update from archesproject: master.

It appears that some changes to the card designer have taken place and these changes may or may not be related to this issue.

The ability to add fully developed branches to each other is essential as otherwise each complex branch has to be built from sctratch.

@Habennin has verified that this bug appears in his instance as well

**Comment by Habennin** [comment]
Hi all, just verifying that I also experience this behaviour.

**Comment by chiatt** [comment]
Issue moved to [archesproject/arches #6347](https://github.com/archesproject/arches/issues/6347) via [**ZenHub**](https://www.zenhub.com/)
