### ISSUE TITLE
Consultation model: mitigations card fails trying to load a condition (node-node data type problem)

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#544]
The mitigations card requires a user to select a corresponding condition, but fails loading condition tiles from the conditions branch.

![Screen Shot 2021-02-18 at 12.07.12 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/6b2f9b0f-cd73-4d0e-9ea5-7f387f85bde2)

**Comment by chiatt** [comment]
Fixed in #7163
