### ISSUE TITLE
Consultations instance in resource editor throw multiple errors

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#546]
Simply loading a consultations instance in the resource editor throws the following errors:

![Screen Shot 2021-02-18 at 12 16 01 PM](https://user-images.githubusercontent.com/815185/108416251-4b504a00-71e3-11eb-8196-e94009599963.png)

**Comment by chiatt** [comment]
These errors were due to issues with the old report template and are now resolved.
