### ISSUE TITLE
Instance tree issue with Consultations model 

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#547]
Clicking on the conditions type branch results in the following error:

![Screen Shot 2021-02-18 at 12 20 10 PM](https://user-images.githubusercontent.com/815185/108416522-ada94a80-71e3-11eb-9ba6-a2aba629e71b.png)

**Comment by chiatt** [comment]
This issue appears to be related to the rendering of the grouping card

**Comment by njkim** [comment]
Fixed in archesproject/arches#8040
