### ISSUE TITLE
Update workflow summary step - Application Area

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#578]
The Arches-HER workflows should be updated so that the final step (eg: summary step) matches the mockups attached[https://app.zenhub.com/files/180664470/5306fbf8-a592-4e97-84c8-93e0148201f1/download](https://app.zenhub.com/files/180664470/5306fbf8-a592-4e97-84c8-93e0148201f1/download)

**Comment by chiatt** [comment]
Complete for all workflows
