### ISSUE TITLE
Consultations Workflow: application areas overlay map pop-up does not show "select" link

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#581]
In the consultations workflow, the first step requires a user to select an application area to relate to the consultation. One way the user should be able to select the appropriate app area is by clicking on it on the map.  To do so, the map pop-up should include a "select" link in the footer that will add the application area as a related resource to the consultation

**Comment by chiatt** [comment]
@dwuthrich This should be fixed in the latest, but let me know if you don't see the link.
