### ISSUE TITLE
Debug Photo Gallery card component

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-her#59]
Currently the Site Visit workflow (which uses the photo-gallery-card.js card-component for the "Photographs" step) breaks when it gets to the Photographs step. This error was replicated in resource editor as well (for Site Visit)

It seems that neither new-tile-step nor set-tile-value components work with this card-component.
It's unclear what the cause is, but console output is: 
`Uncaught TypeError: newtile.data.e60af863-5d48-11e9-b44f-c4b301baab9f is not a function
    at b.<anonymous> (photo-gallery-card.js?_dc=4.4.1:90)`

**Comment by chiatt** [comment]
This solves the problem described in this ticket. However there is still an outstanding issue with the position of the thumbnail gallery addressed here: #243

**Comment by dwuthrich** [comment]
meets requirement
