### ISSUE TITLE
Show workflows nav bar when a user is editing workflows

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#64]
When editing workflows users should see a simpler instead of the main navigation bar:

<img width="1374" alt="Screen Shot 2019-06-17 at 5 40 40 PM" src="https://user-images.githubusercontent.com/1877663/59645518-17c43f00-9127-11e9-896c-05d8cb7a1d05.png">

**Comment by dwuthrich** [comment]
meets requirements
