### ISSUE TITLE
creating workflow not working

### ISSUE THREAD

**Issue by EnisBerk** [archesproject/arches-her#644]
1) I installed the master branch of arches-her. 
2) went to `http://localhost:9010/arches-her/plugins/init-workflow`
3) clicked on Application Area

Returned page is an empty ![image](https://user-images.githubusercontent.com/6451925/119260746-dd9a2c80-bbdc-11eb-98a7-58f3b4ea1e3f.png)

Here is the error from the Django server:
```
views/components/plugins/tabbed-workflow.htm
[23/May/2021 07:17:20] "GET /templates/views/components/simple-switch.htm?_dc=5.1.4 HTTP/1.1" 200 1772
Internal Server Error: /templates/views/components/plugins/application-area.htm
Traceback (most recent call last):
  File "/root/venvs/archesenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/venvs/archesenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view arches.app.views.main.templates didn't return an HttpResponse object. It returned None instead.
[23/May/2021 07:17:20] "GET /templates/views/components/plugins/application-area.htm?_dc=5.1.4 HTTP/1.1" 500 77565
```

I cannot find tabbed-workflow.htm in the folder views/components/plugins/, that file is previously renamed from workflow.htm [commit](https://github.com/archesproject/arches-her/commit/0149fb9626770b9fc6c587fca0f75d7ae5d25aa2), I cannot find workflow.htm file as well.

**Comment by chiatt** [comment]
@EnisBerk What version of arches are you using?

**Comment by EnisBerk** [comment]
Hi @chiatt , 
Thanks for your quick response, I am using 5.1.4. 

```python
➜  ~ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arches
>>> arches.__version__
'5.1.4'
>>> 
```

**Comment by chiatt** [comment]
Hi @EnisBerk, we are currently developing the workflows for Arches-HER against the stable/5.2.x branch, so I am sure that is the cause of the error. Upgrading to the 5.2.x branch will get things working, but bear in mind that we have to officially released Arches-HER.

**Comment by EnisBerk** [comment]
I understand, thanks for your response, I will test Arches-HER against the stable/5.2.x branch soon and let you know the result.
