### ISSUE TITLE
Potentially remove the view mode and toggle button from Consultation report

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#654]
**Describe the issue** - Would it be possible to remove the View Mode and toggle button from the Key Dates box in the Consultation report as they do not seem to be needed for any reason.

**Steps to reproduce**
1) Open the report for this Consultation record - https://esriarches.fargeo.com/arches-her/report/2cf195f8-805b-4f97-9133-cbd94bf5a01f

2) In the Key Dates box, there is a View Mode button and a toggle button that do not seem to be functioning. If these buttons are not necessary then could we remove them, thank you.

![image](https://user-images.githubusercontent.com/78143228/120815252-89316e00-c547-11eb-9c36-dcd1f68c7c5e.png)

**Comment by chiatt** [comment]
This no longer applies to new report templates
