### ISSUE TITLE
Do the min/max and default date values need to be in the Consultation reports?

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#655]
**Describe the issue** - In each section of the Consultation reports other than Conditions/Mitigations, the box on the left hand side contains empty minimum and maximum and default date values. Is it possible to remove these if they do not need to be there?

**Steps to reproduce**
1) Open the report for this Consultation record - https://esriarches.fargeo.com/arches-her/report/2cf195f8-805b-4f97-9133-cbd94bf5a01f

2) In the 

Expected result - the date values in the boxes on the left hand side (Logged Date, Due Date and Completion Date) should not be empty if their value was added on creation or during editing.

Actual result - The minimum and maximum and default date values are confusing so it could be better for them to be removed.

![image](https://user-images.githubusercontent.com/78143228/120816741-f1cd1a80-c548-11eb-8205-345fa888986c.png)

**Comment by chiatt** [comment]
Bug no longer applies to new report templates
