### ISSUE TITLE
Site Visit data not displaying in Consultation reports

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#656]
**Describe the issue** - The Site Visit data for Consultation records is not displaying in the Consultation reports.

**Steps to reproduce**
1) Open this Consultation record's report - https://esriarches.fargeo.com/arches-her/report/2cf195f8-805b-4f97-9133-cbd94bf5a01f

2) Click on the third tab in the report to view the Site Visits - no data is displaying despite it being in the Consultation:
![image](https://user-images.githubusercontent.com/78143228/120825865-b8e57380-c551-11eb-90c1-02157cc75091.png)

![image](https://user-images.githubusercontent.com/78143228/120825908-c569cc00-c551-11eb-903b-fb65b2af095a.png)

**Comment by chiatt** [comment]
Ticket no longer applies due to new, api driven report templates
