### ISSUE TITLE
Navigation to standard app from Consultation app needed 

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#657]
**Describe the issue** - Currently there is navigation from the standard to the Consultations app, but there is no obvious way to toggle back to the standard app when on the Consultation app. You can click on Resources or Admin, but it would be better for users to have a navigation item that obviously takes them back to the standard app.

**Steps to reproduce**
1) Open the standard Keystone app - https://esriarches.fargeo.com/search

2) Click on the Active Consultations navigation button at the end of the nav menu

3) The Consultations app navigation bar has no obvious way to get back to the standard app

![image](https://user-images.githubusercontent.com/78143228/120829220-13340380-c555-11eb-81a4-c782293bc580.png)

**Comment by dwuthrich** [comment]
@rlwilliamss I agree that such it should be easy to switch between the Consultations app and the standard Arches-HER app.  Which page in the standard app should the proposed link return the use to?

**Comment by rlwilliamss** [comment]
Hi @dwuthrich, I think the search page of the standard Arches-HER app would be best, would you agree @chrisdolby-HE?

**Comment by chiatt** [comment]
No longer applies because the consultations nav UI is being replaced with the standard UI, re #697
