### ISSUE TITLE
Seem to be unable to relate certain resource types to Consultation records

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#660]
**Describe the issue** - When creating/editing Consultation records in the resource editor, some resource types are unable to be related, such as Archive Sources and Artefacts. If this is expected behaviour, then those resource types just need to be removed from the Consultation reports so there are no empty related resource values in the reports.

Resource types that can be related in the resource editor are -

- Activities
- Digital Files
- Heritage Assets
- Heritage Areas

**Steps to reproduce**
1) Open the report for this Consultation record  - https://esriarches.fargeo.com/arches-her/report/2cf195f8-805b-4f97-9133-cbd94bf5a01f

2) Scroll down to the Related Resources section - make sure the hide null values toggle is not switched on

3) You can view the headings for the different resources that cannot be related e.g., Archive Source and Bibliographic Source

Unable to relate certain resource types in the resource editor:
![image](https://user-images.githubusercontent.com/78143228/121334187-5c97a080-c911-11eb-89c1-cea76f9f0ead.png)

In the resource editor, only Digital Files, Heritage Assets,  Heritage Areas and Activity records can be added as related resources:
![image](https://user-images.githubusercontent.com/78143228/121334231-64574500-c911-11eb-828d-87b28be5d8ad.png)

The resources that cannot be related still show up in the Consultation reports - leaving null values:
![image](https://user-images.githubusercontent.com/78143228/121334272-6caf8000-c911-11eb-830a-d04ee2c2ae40.png)

**Comment by dwuthrich** [comment]
This is a configuration issue.  To resolve, open Designer and click on the resource models that you want users to be able to relate an instance to
