### ISSUE TITLE
Can we move the Application Area full name field to the top of the workflow step?

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#670]
**Describe the issue** - It would be useful if the Application Area - show application area name show/hide field was placed at the top of the workflow step, rather than at the bottom, so that it is more obvious to users. It would also be nice to have it as a button, rather than a link.

Arches version 5.2

**Steps to reproduce**
1) Open a new Application Area workflow and scroll to the end of the Assign Addresses step

The show Application Area name link with name hidden:

![image](https://user-images.githubusercontent.com/78143228/125756949-6e7f5a97-d0f0-48c6-a625-b45da52e4a16.png)

Application Area name when shown:

![image](https://user-images.githubusercontent.com/78143228/125756995-a769ac9e-b3d9-475d-8226-4be0b8bc33d3.png)

**Comment by StucakeGLHER** [comment]
@rlwilliamss Yes, that would be better, and easier for Users.

**Comment by StucakeGLHER** [comment]
@rlwilliamss @chiatt Thinking about this abit more, and how you would fill in the address/name, to me it actually makes sense to keep this at the end, and its a check to see what you have added above is okay.  Again, there has been some discuss with the GLAAS Advisers and Business Officers about creating AA names, and I think it would be better to wait and just see how they get on actually using Arches.
