### ISSUE TITLE
Consultation workflow appears to not work when adding multiple Reference Numbers or Site Visit Attendees

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#682]
Steps to reproduce:
1)  Open a new Consultation workflow and enter the following for the Consultation GeoJSON step:

- A point located anywhere in London
- Click save and continue

2) Click the Log Date field to enter today's date - the date should automatically enter in both the Log Date and the Target Date fields

3) Click save and continue

4) Enter the following for the Consultation Details/Type step:

- Consultation Type - Condition Application
- Application Type - Appeal
- Development Type - Agricultural development
- Click save and continue

5) Enter the following for the Reference Numbers step:

- Reference - 1234567890
- Reference Type - System Reference Number
- Agency - Ross Harvey
- Click the green Add button
- Add another reference number - 0987654321
- Reference Type - External Reference
- Agency - Rebecca Seakins
- Click the green Add button

6) Click save and continue - the step refreshes and the 2 reference numbers disappear. The only way to move to the next step is to then add a single Reference Number. However, when you get to the summary page, there are now 3 reference numbers added - the 2 previously added and the 3rd one added after.

![image](https://user-images.githubusercontent.com/78143228/127489030-1c73432a-8f79-4b84-b90e-9d193604f63e.png)

Example of duplicated Reference Numbers:

![image](https://user-images.githubusercontent.com/78143228/127493959-9bdeb7ee-cd08-44de-a252-4f79ed98b4be.png)

**Comment by njkim** [comment]
The issue appears to be fixed after workflow upgrade.

**Comment by chiatt** [comment]
Thanks for confirming @njkim. I suspected that was the case.
