### ISSUE TITLE
Can we remove the calendar icon from the date widget?

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#685]
**Issue Description:** (priority 3 enhancement) - Can we remove the calendar icon on the date widget as it is not clickable and confuses the user when no calendar appears. The calendar only appears when you click directly in the field.

![image](https://user-images.githubusercontent.com/78143228/127494598-708fd48f-dbf4-4089-be8e-55f22598639f.png)

**Comment by chrisdolby-HE** [comment]
Additionally, the mouse turns into a hand pointer when it hovers over the calendar icon, which is confusing as it doesn't respond despite the change in appearance.

Either the icon should trigger the calendar widget or should not act in a way that suggests that it would.

**Comment by aj-he** [comment]
@rlwilliamss can this be raised as an Arches feature change rather than arches-her issue as it is a change to the date widget. This can then be closed - please reference the new issue here.

**Comment by rlwilliamss** [comment]
Closed - raised as Arches feature request #8376
