### ISSUE TITLE
Report page hangs after downloading file

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#686]
**Issue Description:** (priority 1 bug) - Report page continues to hang after downloading file - clicking on a download file should target a new tab.

Note from Andy: the file needs to open to a new tab otherwise we are redirected from the record, or if the file is not a file that the browser can display, it downloads and then the loading/waiting overlay gets stuck. Hacking in a target=”_blank” made it work as expected.

Steps to reproduce;
1)  Open the report for a record with an Associated Digital File
2) Scroll to the Associated Digital File(s) section and click on the download link: 

![image](https://user-images.githubusercontent.com/78143228/127497470-b73eff21-2ee1-4fc8-bebf-2b80254339b0.png)

3) The file downloads, but the page continues to hang: 

![image](https://user-images.githubusercontent.com/78143228/127497529-c1c39f6d-2e3e-41d4-a1df-e8872916b186.png)

**Comment by phudson-he** [comment]
@chiatt I've been tasked to look at this and a simple fix would be to add a target="_blank" to the report file download link, tested and working fine. Do you think this fix is viable as a core change?

**Comment by chiatt** [comment]
Thanks @phudson-he for the fix in archesproject/arches#8007
