### ISSUE TITLE
Clicking on overlapping records only brings up the topmost record

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#689]
**Issue Description:** (Priority 1 Bug) Map Overlays – Clicking on overlapping Records only brings up the topmost Record. Please could there be an option to page through the geometries/popups?

E.g., Top record in screenshot below: Coulsdon World War crash site (Heritage Asset)
Record underneath: Hawker Hurricane Mk1 (Historic Aircraft - geometry not visible when Heritage Asset overlay is turned on)

![image](https://user-images.githubusercontent.com/78143228/127498031-ae042f84-75d6-4f99-a855-4c2a9e42339e.png)

**Comment by chiatt** [comment]
re https://github.com/archesproject/arches/issues/5307

**Comment by chiatt** [comment]
resolved in archesproject/arches#8038
