### ISSUE TITLE
Related resource summary section continuously loads when creating new resource

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#694]
**Issues Description** - When creating a new resource within a record in the resource editor, e.g., a new Activity or new Digital Object, if you scroll across the page there is a Related Resource Summary section which appears to be continuously loading. 

**Steps to reproduce**
1) Open a Consultation record in the resource editor

2) Click on the Associated Digital Files card

3) Click on the Files drop down and select to create a new Digital Object to open this view:

![image](https://user-images.githubusercontent.com/78143228/129041966-8403800c-14f6-4cf4-9f5c-ada10ec02ac4.png)

4) Scroll horizontally and you will see the loading summary section:

![image](https://user-images.githubusercontent.com/78143228/129042003-df47add3-5150-46e2-8e1f-6727936b9d5f.png)

**Comment by chiatt** [comment]
@rlwilliamss It's likely that it was fixed in the latest of arches 5.2.x. I'm not able to reproduce this issue, though it could be browser related.  Can pull from the latest on 5.2.x and confirm this problem is still occurring on your machine?

**Comment by rlwilliamss** [comment]
@chiatt I'm no longer getting this issue in the latest version so I'll close this bug, thank you.
