### ISSUE TITLE
Unable to edit large/complex GeoJSON

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#696]
**Describe the issue** - An error occurs when adding or dragging large GeoJSON files to the Location cards. Is the GeoJSON too large?

**Steps to reproduce**
1) Open a new resource in the resource editor - e.g., Place

2) Click on Mapped Location card

3) Click Edit GeoJSON and paste the GeoJSON from the example below

4) Click Add - the following error occurs:

![image](https://user-images.githubusercontent.com/78143228/129576809-a929d9a4-49d5-46ca-aaff-afc61e522820.png)

GeoJSON example London borough of Croydon - [Croydon_Poly (002).geojson.txt](https://github.com/archesproject/arches-her/files/6992965/Croydon_Poly.002.geojson.txt)

**Comment by aj-he** [comment]
@rlwilliamss the coordinates in that geojson file are not using the correct projection - they are certainly not latlong.

**Comment by rlwilliamss** [comment]
@aj-he I'll close this as the issue was not replicable with other large files - this explains why, thank you.

**Comment by rlwilliamss** [comment]
GeoJSON file not using correct projection.
