### ISSUE TITLE
CodeMirror widget 100% height

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-her#703]
The codemirror widget has some troubles getting beyond 300px height (see [heritage asset report branch](https://github.com/archesproject/arches-her/pull/699), unless it's already merged).  The goal is to get the widget to take 100% of the height of the block in which it lives.  (See json tab in aforementioned report)  100% height doesn't seem to do the trick; I've tried various modifications to integrate flex with no success.  There are some [instructions](https://codemirror.net/demo/resize.html) in the codemirror documention for doing this, but I couldn't get them to work and we may need to modify the codemirror bindings to make this happen.

**Comment by aj-he** [comment]
@chiatt can you review/check?

**Comment by chiatt** [comment]
This looks resolved to me in the latest.
