### ISSUE TITLE
Combine first steps in site visit into a single grouped card

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#84]
The first step of the Site Visit workflow should include the:

- Name
- Visit Date
- Related Consultation

**Comment by whatisgalen** [comment]
Made some work on this using the card grouping config object in the site workflow json, putting back in sprint backlog after @chiatt notified of work he's doing to build a custom card component for this.

**Comment by chiatt** [comment]
Closing in favor of #108
