### ISSUE TITLE
Organizations - Remove Named Locations from report

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches-her#846]
Named Locations to be removed from the Organizations report template as it is not in the Organization model.

![image](https://user-images.githubusercontent.com/78143228/152357602-18c6d97d-a306-4ae9-8fe2-51c5e8e9294b.png)

**Comment by Philbox** [comment]
Named Locations don't appear in the Organization model so this is a report issue

**Comment by aj-he** [comment]
fixed in #931
