### ISSUE TITLE
Combine Application Area Name and Address into a single grouped card

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#85]
The first two steps of the Application area workflow should be moved into the same step within a grouped card.

**Comment by dwuthrich** [comment]
per discussion with @chiatt, having the name/address cards grouped is not a requirement for the application area workflow.  Instead, the name card should be displayed in a new step if the user wants to name the application area independently of the address

**Comment by chiatt** [comment]
Closing in favor of #212
