### ISSUE TITLE
Wire up buttons in workflow nav bar

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#88]
The workflow navbar should also persist while a user is working on a workflow.

**Comment by dwuthrich** [comment]
Buttons still don't appear to be functional.  To reproduce: start a workflow and then press the "Quit" button in the upper right.  Note that nothing happens

**Comment by chiatt** [comment]
Hey @dwuthrich This ticket applies to just the step navigation buttons. The Quit and Finish buttons are addressed in different tickets.

**Comment by dwuthrich** [comment]
meets requirements
