### ISSUE TITLE
Create workflow step to identify the target consultation 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#90]
This workflow step will apply to the Site Visit, Communication, and Correspondence workflows.  In some cases this will be combined with other cards in the workflow step.

**Comment by robgaston** [comment]
There appears to be an issue here with advancing past the step after selecting the resource instance.

**Comment by whatisgalen** [comment]
was unable to reproduce -- possibly related to the (since resolved) communications workflow unable to proceed to next step due to lack of nodegroupid
