### ISSUE TITLE
update “Active Consultations” to the latest graphs and parse the display values

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-her#93]
original ticket: #31 

The second item could be approached using a django view specifically for active consultations, or else there's likely some way from the frontend to get the display values needed, likely by loading node_x_cards_x_widgets records. The key takeaway is that there's a range of data types used in the template.

**Comment by apeters** [comment]
fixed in the latest

**Comment by apeters** [comment]
fixed in the latest
